name: Python CI

# Trigger the workflow on any push to the main branch or on any pull request targeting the main branch
on:
    push:
        branches: 
            - main
    pull_request:
        branches: 
            - main

jobs:
    test_pipeline:
        runs-on: ubuntu-latest # container or virtual machine provided by GitHub Actions

        steps:
            # step 1: Check out the code from the repository
            - name: Check out code
              uses: actions/checkout@v2
            
            # step 2: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            
            # step 3: Install dependencies and run tests
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            # step 4: Run tests using pytest
            - name: Run tests
              run: pytest tests/
            

